name: Default

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2', '8.3', '8.4']
        phpunit-versions: ['^10.0', '^11.0', '^12.0']

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit:${{ matrix.phpunit-versions }}

      - name: Print PHP version
        run: php -v

      - name: Print PHPUnit version
        run: vendor/bin/phpunit --version

      - name: Check coding standard
        run: vendor/bin/phpcs -p

      - name: Analyze with PHPStan
        run: vendor/bin/phpstan analyse

      - name: Execute PHPUnit tests
        run: vendor/bin/phpunit
